version: '3.4'

networks:
  backend:

services:
  postdb:
    container_name: post-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password@12345#
      - MSSQL_PID=Evaluation
    networks:
      - backend
    ports:
      - 8001:1433   
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    networks:
      - backend
    ports:
      - 8002:8080
      - 8003:8081
    environment:
      - DB_HOST= postdb
      - DB_NAME=PostDb
      - DB_SA_PASSWORD=password@12345#
    depends_on:
      - postdb
  
